import {
  createLlamaFamilySurface,
  type LlamaFamilySurfaceOptions,
} from "../runtime/llama_family_surface.js";

type AdapterLlamaSessionFacade = Readonly<{
  position: LlamaFamilySurfaceOptions["llamaSessionPositionFacade"];
  inspect: LlamaFamilySurfaceOptions["inspectLlamaSessionFacade"];
  bufferLayout: LlamaFamilySurfaceOptions["llamaSessionBufferLayout"];
  bufferSlotNames: LlamaFamilySurfaceOptions["llamaSessionBufferSlotNames"];
  bufferSlot: LlamaFamilySurfaceOptions["llamaSessionBufferSlot"];
  kvCacheLayout: LlamaFamilySurfaceOptions["llamaSessionKvCacheLayout"];
  inputLen: LlamaFamilySurfaceOptions["llamaSessionInputLen"];
  outputLen: LlamaFamilySurfaceOptions["llamaSessionOutputLen"];
  inputByteLength: LlamaFamilySurfaceOptions["llamaSessionInputByteLength"];
  outputByteLength: LlamaFamilySurfaceOptions["llamaSessionOutputByteLength"];
  weightsLen: LlamaFamilySurfaceOptions["llamaSessionWeightsLen"];
  weightsByteLength: LlamaFamilySurfaceOptions["llamaSessionWeightsByteLength"];
  biasLen: LlamaFamilySurfaceOptions["llamaSessionBiasLen"];
  biasByteLength: LlamaFamilySurfaceOptions["llamaSessionBiasByteLength"];
  parameterLen: LlamaFamilySurfaceOptions["llamaSessionParameterLen"];
  parameterByteLength: LlamaFamilySurfaceOptions["llamaSessionParameterByteLength"];
  bufferSizing: LlamaFamilySurfaceOptions["llamaSessionBufferSizing"];
  matchesBufferSizingSignature: LlamaFamilySurfaceOptions["llamaSessionMatchesBufferSizingSignature"];
  outputShape: LlamaFamilySurfaceOptions["llamaSessionOutputShape"];
  stepContract: LlamaFamilySurfaceOptions["llamaSessionStepContract"];
  stepParamsCompatibility: LlamaFamilySurfaceOptions["llamaSessionStepParamsCompatibility"];
  preflightStepParams: LlamaFamilySurfaceOptions["llamaSessionPreflightStepParams"];
  acceptsStepParams: LlamaFamilySurfaceOptions["llamaSessionAcceptsStepParams"];
  canExecuteStepParams: LlamaFamilySurfaceOptions["llamaSessionCanExecuteStepParams"];
  requireCanExecuteStepParams: LlamaFamilySurfaceOptions["llamaSessionRequireCanExecuteStepParams"];
  acceptsAllocationFreeStepParams: LlamaFamilySurfaceOptions["llamaSessionAcceptsAllocationFreeStepParams"];
  requireAllocationFreeStepParams: LlamaFamilySurfaceOptions["llamaSessionRequireAllocationFreeStepParams"];
  acceptsRuntimeOutputAllocationFreeStepParams: LlamaFamilySurfaceOptions["llamaSessionAcceptsRuntimeOutputAllocationFreeStepParams"];
  requireRuntimeOutputAllocationFreeStepParams: LlamaFamilySurfaceOptions["llamaSessionRequireRuntimeOutputAllocationFreeStepParams"];
  acceptsNoReadbackStepParams: LlamaFamilySurfaceOptions["llamaSessionAcceptsNoReadbackStepParams"];
  requireNoReadbackStepParams: LlamaFamilySurfaceOptions["llamaSessionRequireNoReadbackStepParams"];
  acceptsReadbackFreeStepParams: LlamaFamilySurfaceOptions["llamaSessionAcceptsReadbackFreeStepParams"];
  requireReadbackFreeStepParams: LlamaFamilySurfaceOptions["llamaSessionRequireReadbackFreeStepParams"];
  acceptsHotStepParams: LlamaFamilySurfaceOptions["llamaSessionAcceptsHotStepParams"];
  requireHotStepParams: LlamaFamilySurfaceOptions["llamaSessionRequireHotStepParams"];
  executionPlan: LlamaFamilySurfaceOptions["llamaSessionExecutionPlan"];
  requireExecutionPlan: LlamaFamilySurfaceOptions["llamaSessionRequireExecutionPlan"];
  hotPathPlan: LlamaFamilySurfaceOptions["llamaSessionHotPathPlan"];
  matchesStepContractSignature: LlamaFamilySurfaceOptions["llamaSessionMatchesStepContractSignature"];
  matchesStepParamsSignature: LlamaFamilySurfaceOptions["llamaSessionMatchesStepParamsSignature"];
  matchesStepParamsCompatibility: LlamaFamilySurfaceOptions["llamaSessionMatchesStepParamsCompatibility"];
  step: LlamaFamilySurfaceOptions["stepLlama"];
  stepTensor: LlamaFamilySurfaceOptions["stepLlamaTensor"];
  stepInto: LlamaFamilySurfaceOptions["stepLlamaInto"];
  scalarTokenWindow: LlamaFamilySurfaceOptions["llamaScalarTokenWindow"];
  sessionScalarTokenSampleOptions: LlamaFamilySurfaceOptions["llamaScalarTokenSampleOptions"];
  sessionNoOutputTokenWindowOptions: LlamaFamilySurfaceOptions["llamaNoOutputTokenWindowOptions"];
  sessionOutputTokenWindowOptions: LlamaFamilySurfaceOptions["llamaOutputTokenWindowOptions"];
  sessionScalarTokenExecuteOptions: LlamaFamilySurfaceOptions["llamaScalarTokenExecuteOptions"];
  sessionScalarTokenOutputOptions: LlamaFamilySurfaceOptions["llamaScalarTokenOutputOptions"];
  advance: LlamaFamilySurfaceOptions["advanceLlama"];
  advanceTokens: LlamaFamilySurfaceOptions["advanceLlamaTokens"];
  executeTokensArgmax: LlamaFamilySurfaceOptions["executeLlamaTokensArgmax"];
  stepArgmax: LlamaFamilySurfaceOptions["stepLlamaArgmax"];
  executeTokensSample: LlamaFamilySurfaceOptions["executeLlamaTokensSample"];
  stepSample: LlamaFamilySurfaceOptions["stepLlamaSample"];
  generateTokensArgmax: LlamaFamilySurfaceOptions["generateLlamaTokensArgmax"];
  generateTokensArgmaxInto: LlamaFamilySurfaceOptions["generateLlamaTokensArgmaxInto"];
  generateTokensSample: LlamaFamilySurfaceOptions["generateLlamaTokensSample"];
  generateTokensSampleInto: LlamaFamilySurfaceOptions["generateLlamaTokensSampleInto"];
  executeTokens: LlamaFamilySurfaceOptions["executeLlamaTokens"];
  execute: LlamaFamilySurfaceOptions["executeLlama"];
  executeTensor: LlamaFamilySurfaceOptions["executeLlamaTensor"];
  executeInto: LlamaFamilySurfaceOptions["executeLlamaInto"];
  argmaxToken: LlamaFamilySurfaceOptions["argmaxLlamaToken"];
  sampleToken: LlamaFamilySurfaceOptions["sampleLlamaToken"];
  prefill: LlamaFamilySurfaceOptions["prefillLlama"];
  prefillTensor: LlamaFamilySurfaceOptions["prefillLlamaTensor"];
  prefillInto: LlamaFamilySurfaceOptions["prefillLlamaInto"];
  readOutputInto: LlamaFamilySurfaceOptions["readLlamaOutputInto"];
  readOutputTensor: LlamaFamilySurfaceOptions["readLlamaOutputTensor"];
  sessionCallProfile: LlamaFamilySurfaceOptions["llamaSessionCallProfileFacade"];
  matchesSessionCallProfileSignature: LlamaFamilySurfaceOptions["llamaSessionMatchesCallProfileSignature"];
  resetSessionCallProfile: LlamaFamilySurfaceOptions["resetLlamaSessionCallProfileFacade"];
  reset: LlamaFamilySurfaceOptions["resetLlamaSessionFacade"];
  runtimeProfile: LlamaFamilySurfaceOptions["llamaSessionRuntimeProfileFacade"];
  matchesRuntimeProfileSignature: LlamaFamilySurfaceOptions["llamaSessionMatchesRuntimeProfileSignature"];
  resetRuntimeProfile: LlamaFamilySurfaceOptions["resetLlamaSessionRuntimeProfileFacade"];
  free: LlamaFamilySurfaceOptions["freeLlamaSessionFacade"];
  dispose: LlamaFamilySurfaceOptions["disposeLlamaSessionFacade"];
}>;

export type AdapterLlamaFamilySurfaceOptions = Readonly<{
  autoKind: LlamaFamilySurfaceOptions["autoKind"];
  tinyLlamaKind: LlamaFamilySurfaceOptions["tinyLlamaKind"];
  smollm135mKind: LlamaFamilySurfaceOptions["smollm135mKind"];
  llamaModelFamilyFacade: LlamaFamilySurfaceOptions["llamaModelFamilyFacade"];
  llamaProgramFacade: LlamaFamilySurfaceOptions["llamaProgramFacade"];
  bindLlamaSessionHandle: LlamaFamilySurfaceOptions["bindLlamaSessionHandle"];
  defaultLlamaSessionBufferLayout: LlamaFamilySurfaceOptions["defaultLlamaSessionBufferLayout"];
  createLlamaSessionScratch: LlamaFamilySurfaceOptions["createLlamaSessionScratch"];
  assertSessionAlive: LlamaFamilySurfaceOptions["assertSessionAlive"];
  llamaSessionFacade: AdapterLlamaSessionFacade;
}>;

export function createAdapterLlamaFamilySurface(options: AdapterLlamaFamilySurfaceOptions) {
  const session = options.llamaSessionFacade;
  return createLlamaFamilySurface({
    autoKind: options.autoKind,
    tinyLlamaKind: options.tinyLlamaKind,
    smollm135mKind: options.smollm135mKind,
    llamaModelFamilyFacade: options.llamaModelFamilyFacade,
    llamaProgramFacade: options.llamaProgramFacade,
    bindLlamaSessionHandle: options.bindLlamaSessionHandle,
    defaultLlamaSessionBufferLayout: options.defaultLlamaSessionBufferLayout,
    createLlamaSessionScratch: options.createLlamaSessionScratch,
    assertSessionAlive: options.assertSessionAlive,
    llamaSessionPositionFacade: session.position,
    inspectLlamaSessionFacade: session.inspect,
    llamaSessionBufferLayout: session.bufferLayout,
    llamaSessionBufferSlotNames: session.bufferSlotNames,
    llamaSessionBufferSlot: session.bufferSlot,
    llamaSessionKvCacheLayout: session.kvCacheLayout,
    llamaSessionInputLen: session.inputLen,
    llamaSessionOutputLen: session.outputLen,
    llamaSessionInputByteLength: session.inputByteLength,
    llamaSessionOutputByteLength: session.outputByteLength,
    llamaSessionWeightsLen: session.weightsLen,
    llamaSessionWeightsByteLength: session.weightsByteLength,
    llamaSessionBiasLen: session.biasLen,
    llamaSessionBiasByteLength: session.biasByteLength,
    llamaSessionParameterLen: session.parameterLen,
    llamaSessionParameterByteLength: session.parameterByteLength,
    llamaSessionBufferSizing: session.bufferSizing,
    llamaSessionMatchesBufferSizingSignature: session.matchesBufferSizingSignature,
    llamaSessionOutputShape: session.outputShape,
    llamaSessionStepContract: session.stepContract,
    llamaSessionStepParamsCompatibility: session.stepParamsCompatibility,
    llamaSessionPreflightStepParams: session.preflightStepParams,
    llamaSessionAcceptsStepParams: session.acceptsStepParams,
    llamaSessionCanExecuteStepParams: session.canExecuteStepParams,
    llamaSessionRequireCanExecuteStepParams: session.requireCanExecuteStepParams,
    llamaSessionAcceptsAllocationFreeStepParams: session.acceptsAllocationFreeStepParams,
    llamaSessionRequireAllocationFreeStepParams: session.requireAllocationFreeStepParams,
    llamaSessionAcceptsRuntimeOutputAllocationFreeStepParams: session.acceptsRuntimeOutputAllocationFreeStepParams,
    llamaSessionRequireRuntimeOutputAllocationFreeStepParams: session.requireRuntimeOutputAllocationFreeStepParams,
    llamaSessionAcceptsNoReadbackStepParams: session.acceptsNoReadbackStepParams,
    llamaSessionRequireNoReadbackStepParams: session.requireNoReadbackStepParams,
    llamaSessionAcceptsReadbackFreeStepParams: session.acceptsReadbackFreeStepParams,
    llamaSessionRequireReadbackFreeStepParams: session.requireReadbackFreeStepParams,
    llamaSessionAcceptsHotStepParams: session.acceptsHotStepParams,
    llamaSessionRequireHotStepParams: session.requireHotStepParams,
    llamaSessionExecutionPlan: session.executionPlan,
    llamaSessionRequireExecutionPlan: session.requireExecutionPlan,
    llamaSessionHotPathPlan: session.hotPathPlan,
    llamaSessionMatchesStepContractSignature: session.matchesStepContractSignature,
    llamaSessionMatchesStepParamsSignature: session.matchesStepParamsSignature,
    llamaSessionMatchesStepParamsCompatibility: session.matchesStepParamsCompatibility,
    stepLlama: session.step,
    stepLlamaTensor: session.stepTensor,
    stepLlamaInto: session.stepInto,
    llamaScalarTokenWindow: session.scalarTokenWindow,
    llamaScalarTokenSampleOptions: session.sessionScalarTokenSampleOptions,
    llamaNoOutputTokenWindowOptions: session.sessionNoOutputTokenWindowOptions,
    llamaOutputTokenWindowOptions: session.sessionOutputTokenWindowOptions,
    llamaScalarTokenExecuteOptions: session.sessionScalarTokenExecuteOptions,
    llamaScalarTokenOutputOptions: session.sessionScalarTokenOutputOptions,
    advanceLlama: session.advance,
    advanceLlamaTokens: session.advanceTokens,
    executeLlamaTokensArgmax: session.executeTokensArgmax,
    stepLlamaArgmax: session.stepArgmax,
    executeLlamaTokensSample: session.executeTokensSample,
    stepLlamaSample: session.stepSample,
    generateLlamaTokensArgmax: session.generateTokensArgmax,
    generateLlamaTokensArgmaxInto: session.generateTokensArgmaxInto,
    generateLlamaTokensSample: session.generateTokensSample,
    generateLlamaTokensSampleInto: session.generateTokensSampleInto,
    executeLlamaTokens: session.executeTokens,
    executeLlama: session.execute,
    executeLlamaTensor: session.executeTensor,
    executeLlamaInto: session.executeInto,
    argmaxLlamaToken: session.argmaxToken,
    sampleLlamaToken: session.sampleToken,
    prefillLlama: session.prefill,
    prefillLlamaTensor: session.prefillTensor,
    prefillLlamaInto: session.prefillInto,
    readLlamaOutputInto: session.readOutputInto,
    readLlamaOutputTensor: session.readOutputTensor,
    llamaSessionCallProfileFacade: session.sessionCallProfile,
    llamaSessionMatchesCallProfileSignature: session.matchesSessionCallProfileSignature,
    resetLlamaSessionCallProfileFacade: session.resetSessionCallProfile,
    resetLlamaSessionFacade: session.reset,
    llamaSessionRuntimeProfileFacade: session.runtimeProfile,
    llamaSessionMatchesRuntimeProfileSignature: session.matchesRuntimeProfileSignature,
    resetLlamaSessionRuntimeProfileFacade: session.resetRuntimeProfile,
    freeLlamaSessionFacade: session.free,
    disposeLlamaSessionFacade: session.dispose,
  });
}
