type KoffiStructRegistrar = {
  struct(name: string, fields: Record<string, string>): unknown;
};

function requireKoffiStructRegistrar(value: unknown): KoffiStructRegistrar {
  if (
    value === null ||
    typeof value !== "object" ||
    typeof (value as { struct?: unknown }).struct !== "function"
  ) {
    throw new TypeError("zgml Node runtime expected a Koffi module with struct()");
  }
  return value as KoffiStructRegistrar;
}

export type NodeAbiStructs = Readonly<Record<string, unknown>>;

export function registerNodeAbiStructs(koffi: unknown): NodeAbiStructs {
  const api = requireKoffiStructRegistrar(koffi);

  return Object.freeze({
    ModelDesc: api.struct("zgml_model_desc", {
      kind: "uint32_t",
      activation: "uint32_t",
      input_len: "size_t",
      output_len: "size_t",
      hidden_len: "size_t",
    }),
    ModelLoadDesc: api.struct("zgml_model_load_desc", {
      kind: "uint32_t",
      path: "const char *",
      path_len: "size_t",
    }),
    SafetensorsHeaderProbeDesc: api.struct("zgml_safetensors_header_probe_desc", {
      kind: "uint32_t",
      reserved: "uint32_t",
      header: "const char *",
      header_len: "size_t",
    }),
    SafetensorsDataLoadDesc: api.struct("zgml_safetensors_data_load_desc", {
      kind: "uint32_t",
      reserved: "uint32_t",
      data: "const void *",
      data_len: "size_t",
    }),
    ModelInspection: api.struct("zgml_model_inspection", {
      model_kind: "uint32_t",
      reserved: "uint32_t",
      input_len: "uint64_t",
      output_len: "uint64_t",
      vocab_size: "uint64_t",
      max_seq_len: "uint64_t",
      d_model: "uint64_t",
      n_layers: "uint64_t",
      n_heads: "uint64_t",
      n_kv_heads: "uint64_t",
      d_ff: "uint64_t",
      rope_base: "double",
      rms_norm_eps: "double",
      tied_lm_head: "uint64_t",
    }),
    ProgramModelCompatibility: api.struct("zgml_program_model_compatibility", {
      program_model_kind: "uint32_t",
      model_kind: "uint32_t",
      compatible: "uint64_t",
    }),
    SessionInspection: api.struct("zgml_session_inspection", {
      model_kind: "uint32_t",
      backend: "uint32_t",
      output_storage: "uint32_t",
      kv_cache_storage: "uint32_t",
      position: "uint64_t",
      context_len: "uint64_t",
      persistent_binding_count: "uint64_t",
      step_input_count: "uint64_t",
      step_output_count: "uint64_t",
      host_binding_count: "uint64_t",
      resource_binding_count: "uint64_t",
      binding_shape_hash: "uint64_t",
    }),
    CompileDesc: api.struct("zgml_compile_desc", {
      backend: "uint32_t",
      reserved: "uint32_t",
      context_len: "size_t",
      batch: "size_t",
    }),
    ModuleDesc: api.struct("zgml_module_desc", {
      input_shape: "const void *",
      input_rank: "size_t",
      ops: "const void *",
      op_count: "size_t",
    }),
    BindDesc: api.struct("zgml_bind_desc", {
      weights: "const float *",
      weights_len: "size_t",
      bias: "const float *",
      bias_len: "size_t",
      input: "const float *",
      input_len: "size_t",
      output: "float *",
      output_len: "size_t",
    }),
    BufferDesc: api.struct("zgml_buffer_desc", {
      byte_len: "size_t",
    }),
    BufferInspection: api.struct("zgml_buffer_inspection", {
      storage: "uint32_t",
      placement: "uint32_t",
      access_flags: "uint32_t",
      reserved: "uint32_t",
      byte_len: "uint64_t",
      handle: "uint64_t",
      byte_offset: "uint64_t",
      resource_byte_len: "uint64_t",
    }),
    ExternalResourceDesc: api.struct("zgml_external_resource_desc", {
      placement: "uint32_t",
      access_flags: "uint32_t",
      handle: "size_t",
      byte_offset: "size_t",
      byte_len: "size_t",
    }),
    DeviceBufferImportDesc: api.struct("zgml_device_buffer_import_desc", {
      placement: "uint32_t",
      reserved: "uint32_t",
      device_handle: "size_t",
      buffer_handle: "size_t",
      byte_offset: "size_t",
      byte_len: "size_t",
    }),
    BufferBindDesc: api.struct("zgml_buffer_bind_desc", {
      weights: "void *",
      weights_len: "size_t",
      bias: "void *",
      bias_len: "size_t",
      input: "void *",
      input_len: "size_t",
      output: "void *",
      output_len: "size_t",
    }),
    LlamaKvCacheBindDesc: api.struct("zgml_llama_kv_cache_bind_desc", {
      k: "void **",
      v: "void **",
      len: "size_t",
    }),
    LlamaBufferBindDesc: api.struct("zgml_llama_buffer_bind_desc", {
      output: "void *",
      output_len: "size_t",
      kv_cache: "const zgml_llama_kv_cache_bind_desc *",
    }),
    StepDesc: api.struct("zgml_step_desc", {
      input: "const float *",
      input_len: "size_t",
      output: "float *",
      output_len: "size_t",
    }),
    StepResult: api.struct("zgml_step_result", {
      output_len: "size_t",
    }),
    TokenStepDesc: api.struct("zgml_token_step_desc", {
      token: "uint32_t",
      output: "float *",
      output_len: "size_t",
    }),
    ProgramInspection: api.struct("zgml_program_inspection", {
      backend: "uint64_t",
      execution_supported: "uint64_t",
      external_resources_supported: "uint64_t",
      buffer_count: "uint64_t",
      buffer_byte_len: "uint64_t",
      initial_upload_count: "uint64_t",
      qweight_count: "uint64_t",
      command_count: "uint64_t",
      command_stencil_hash: "uint64_t",
      runtime_patch_holes: "uint64_t",
      runtime_patch_cache_write_pos_holes: "uint64_t",
      runtime_patch_attention_seq_kv_holes: "uint64_t",
      runtime_patch_stencil_hash: "uint64_t",
      command_op_count: "uint64_t",
      command_row_count: "uint64_t",
      command_projection_count: "uint64_t",
      command_attention_count: "uint64_t",
      command_movement_count: "uint64_t",
      command_elementwise_count: "uint64_t",
      command_rope_count: "uint64_t",
      op_count: "uint64_t",
      buffer_element_count: "uint64_t",
      runtime_patch_max_cache_write_pos: "uint64_t",
      runtime_patch_max_attention_seq_kv: "uint64_t",
      backend_dispatch_count: "uint64_t",
      dispatch_plan_supported: "uint64_t",
      dispatch_plan_covered_op_count: "uint64_t",
      dispatch_plan_first_unsupported_op: "uint64_t",
      dispatch_plan_projection_count: "uint64_t",
      dispatch_plan_row_count: "uint64_t",
      dispatch_plan_attention_count: "uint64_t",
      dispatch_plan_movement_count: "uint64_t",
      dispatch_plan_elementwise_count: "uint64_t",
      dispatch_plan_rope_count: "uint64_t",
      dispatch_plan_quantized_projection_count: "uint64_t",
      binding_requirement_hash: "uint64_t",
      persistent_requirement_count: "uint64_t",
      step_input_requirement_count: "uint64_t",
      step_output_requirement_count: "uint64_t",
    }),
    LlamaProgramInspection: api.struct("zgml_llama_program_inspection", {
      vocab_size: "uint64_t",
      max_seq_len: "uint64_t",
      context_len: "uint64_t",
      batch: "uint64_t",
      d_model: "uint64_t",
      n_layers: "uint64_t",
      n_heads: "uint64_t",
      n_kv_heads: "uint64_t",
      semantic_stage_count: "uint64_t",
      semantic_token_count: "uint64_t",
      semantic_layer_stage_count: "uint64_t",
      semantic_terminal_stage_count: "uint64_t",
      semantic_runtime_patch_holes: "uint64_t",
      semantic_runtime_patch_cache_write_pos_holes: "uint64_t",
      semantic_runtime_patch_attention_seq_kv_holes: "uint64_t",
    }),
    LlamaKvCacheRequirements: api.struct("zgml_llama_kv_cache_requirements", {
      model_kind: "uint32_t",
      scalar_bytes: "uint32_t",
      n_layers: "uint32_t",
      reserved: "uint32_t",
      context_len: "size_t",
      k_buffer_byte_len: "size_t",
      v_buffer_byte_len: "size_t",
      buffer_byte_len: "size_t",
    }),
    RuntimeProfile: api.struct("zgml_runtime_profile", {
      call_count: "uint64_t",
      backend_op_count: "uint64_t",
      fallback_op_count: "uint64_t",
      backend_dispatch_count: "uint64_t",
      sync_count: "uint64_t",
      runtime_patch_call_count: "uint64_t",
      runtime_patch_changed_count: "uint64_t",
      runtime_patch_invalid_count: "uint64_t",
      runtime_patch_holes: "uint64_t",
      runtime_patch_cache_write_pos_holes: "uint64_t",
      runtime_patch_attention_seq_kv_holes: "uint64_t",
      runtime_patch_stencil_hash: "uint64_t",
      command_count: "uint64_t",
      command_stencil_hash: "uint64_t",
      command_op_count: "uint64_t",
      command_row_count: "uint64_t",
      command_projection_count: "uint64_t",
      command_attention_count: "uint64_t",
      command_movement_count: "uint64_t",
      command_elementwise_count: "uint64_t",
      command_rope_count: "uint64_t",
    }),
    TokenExecuteDesc: api.struct("zgml_token_execute_desc", {
      tokens: "const uint32_t *",
      tokens_len: "size_t",
      output_policy: "uint32_t",
      reserved: "uint32_t",
      output: "float *",
      output_len: "size_t",
    }),
    TokenAdvanceDesc: api.struct("zgml_token_advance_desc", {
      token: "uint32_t",
    }),
    TokenArgmaxDesc: api.struct("zgml_token_argmax_desc", {
      logits: "const float *",
      logits_len: "size_t",
      reserved: "uint32_t",
    }),
    TokenArgmaxResult: api.struct("zgml_token_argmax_result", {
      token: "uint32_t",
      logit: "float",
    }),
    TokenExecuteArgmaxDesc: api.struct("zgml_token_execute_argmax_desc", {
      tokens: "const uint32_t *",
      tokens_len: "size_t",
      reserved: "uint32_t",
    }),
    TokenGenerateArgmaxDesc: api.struct("zgml_token_generate_argmax_desc", {
      tokens: "const uint32_t *",
      tokens_len: "size_t",
      output_tokens: "uint32_t *",
      output_tokens_len: "size_t",
      reserved: "uint32_t",
    }),
    TokenGenerateArgmaxResult: api.struct("zgml_token_generate_argmax_result", {
      tokens_generated: "size_t",
      last_token: "uint32_t",
      last_logit: "float",
    }),
    TokenSampleDesc: api.struct("zgml_token_sample_desc", {
      logits: "const float *",
      logits_len: "size_t",
      top_k: "uint32_t",
      seed: "uint32_t",
      temperature: "float",
      reserved: "uint32_t",
    }),
    TokenSampleResult: api.struct("zgml_token_sample_result", {
      token: "uint32_t",
      logit: "float",
    }),
    TokenExecuteSampleDesc: api.struct("zgml_token_execute_sample_desc", {
      tokens: "const uint32_t *",
      tokens_len: "size_t",
      top_k: "uint32_t",
      seed: "uint32_t",
      temperature: "float",
      reserved: "uint32_t",
    }),
    TokenGenerateSampleDesc: api.struct("zgml_token_generate_sample_desc", {
      tokens: "const uint32_t *",
      tokens_len: "size_t",
      output_tokens: "uint32_t *",
      output_tokens_len: "size_t",
      top_k: "uint32_t",
      seed: "uint32_t",
      temperature: "float",
      reserved: "uint32_t",
    }),
    TokenGenerateSampleResult: api.struct("zgml_token_generate_sample_result", {
      tokens_generated: "size_t",
      last_token: "uint32_t",
      last_logit: "float",
    }),
    ProgramRequirements: api.struct("zgml_program_requirements", {
      model_kind: "uint32_t",
      scalar_bytes: "uint32_t",
      token_id_bytes: "uint32_t",
      reserved: "uint32_t",
      input_len: "size_t",
      input_byte_len: "size_t",
      output_len: "size_t",
      weights_len: "size_t",
      weights_byte_len: "size_t",
      bias_len: "size_t",
      bias_byte_len: "size_t",
      parameter_len: "size_t",
      parameter_byte_len: "size_t",
      logits_len: "size_t",
      output_byte_len: "size_t",
      context_len: "size_t",
      batch: "size_t",
      max_token_window: "size_t",
    }),
    RuntimeInfo: api.struct("zgml_runtime_info", {
      abi_version: "uint32_t",
      size_t_bytes: "uint32_t",
      pointer_bytes: "uint32_t",
      token_id_bytes: "uint32_t",
      feature_flags: "uint64_t",
    }),
  });
}
