// @ts-nocheck

const {
  createNodeFfiBootstrap,
} = require("./node_ffi_bootstrap.js");
const {
  createNodeSymbolGroups,
} = require("./node_symbol_groups.js");
const {
  createNodeLlamaTokenOps,
} = require("./node_llama_token_ops.js");
const {
  createNodeModelSourceOps,
} = require("./node_model_source_ops.js");
const {
  createNodeModelSourceBytes,
} = require("./node_model_source_bytes.js");
const {
  createAdapterModelSourceSurface,
} = require("./model_source_surface.js");
const {
  createAdapterModelSourceFacade,
} = require("./model_source_facade.js");
const {
  createAdapterModelHandlePolicy,
} = require("./model_handle_policy.js");
const {
  createNodeInspectionOps,
} = require("./node_inspection_ops.js");
const {
  createNodeLlamaSessionBindOps,
} = require("./node_llama_session_bind_ops.js");
const {
  createNodeModuleProgramOps,
} = require("./node_module_program_ops.js");
const {
  createAdapterProgramFactory,
} = require("./program_factory_surface.js");
const {
  createAdapterModuleCompilerSurface,
} = require("./module_compiler_surface.js");
const {
  createAdapterModuleStateSurface,
} = require("./module_state_surface.js");
const {
  createAdapterProgramRuntimeSurface,
} = require("./program_runtime_surface.js");
const {
  createNodeLlamaKvCacheOps,
} = require("./node_llama_kv_cache_ops.js");
const {
  createNodeLlamaKvCacheClass,
} = require("./node_llama_kv_cache_surface.js");
const {
  createNodeLlamaKvCacheFactorySurface,
} = require("./node_llama_kv_cache_factory_surface.js");
const {
  createNodeProgramBufferOps,
} = require("./node_program_buffer_ops.js");
const {
  createAdapterProgramBufferNativeBridge,
} = require("./program_buffer_native_bridge.js");
const {
  createAdapterProgramBufferFactorySurface,
} = require("./program_buffer_factory_surface.js");
const {
  createNodeSessionOps,
} = require("./node_session_ops.js");
const {
  createNodeProgramBindOps,
} = require("./node_program_bind_ops.js");
const {
  createAdapterSessionFactory,
} = require("./session_factory_surface.js");
const {
  createAdapterSessionRuntimeSurface,
} = require("./session_runtime_surface.js");
const {
  createAdapterLlamaSessionFacadeSurface,
} = require("./llama_session_facade_surface.js");
const {
  createAdapterTensorRuntimeSurface,
} = require("./tensor_runtime_surface.js");
const {
  createAdapterLlamaFamilySurface,
} = require("./llama_family_surface.js");
const {
  createNodeGenericFamilySurface,
} = require("./node_generic_family_surface.js");
const {
  NativeBuffer: AdapterNativeBuffer,
  setAdapterNativeBufferFacade,
} = require("./native_buffer_surface.js");
const {
  Tensor,
  setAdapterTensorSurfaceHelpers,
} = require("./tensor_surface.js");
const {
  createAdapterPublicRuntimeExports,
} = require("./public_runtime_exports_surface.js");
const {
  createAdapterCompileNamespace,
  createAdapterFrontendNamespaces,
  createAdapterTorchCheckpointIo,
  createAdapterTorchNamespace,
} = require("./frontend_namespace_surface.js");
const {
  createAdapterFrontendModuleSurface,
} = require("./frontend_module_surface.js");
const {
  createAdapterSafetensorsFileHeaderHelpers,
} = require("./safetensors_file_header.js");
const {
  createAdapterNativeBufferInstanceSurface,
} = require("./native_buffer_instance_surface.js");
const {
  createAdapterNativeBufferFacadeSurface,
} = require("./native_buffer_facade_surface.js");
const {
  createNodeNativeBufferSyscalls,
} = require("./node_native_buffer_syscalls.js");
const {
  createNodeNativeLifecycleOps,
} = require("./node_native_lifecycle_ops.js");
const {
  requireNodeSharedFrontendRuntime,
} = require("./node_shared_frontend_runtime.js");
const {
  createAdapterSharedFrontendProjection,
} = require("./shared_frontend_projection.js");
const {
  readFileSync,
  writeFileSync,
} = require("node:fs");
const {
  createAdapterDeferredSlot,
} = require("./deferred_slot.js");
const {
  webgpuInterop,
} = require("./webgpu_interop.js");
const {
  adapterBufferStorageAliases,
  adapterModelKindAliases,
} = require("../runtime/native_abi_constants.js");
const {
  createAdapterIndexValuesSurface,
} = require("./index_values_surface.js");
const {
  createAdapterGradModeSurface,
} = require("./grad_mode_surface.js");
const {
  fs,
  symbols,
  ZgmlError,
  check,
  handleOut,
  readHandle,
  assertAlive,
  runtimeInfo,
  abiStructSize,
  abiStructSizes,
  loadedRuntimeInfo,
} = createNodeFfiBootstrap({ dirname: __dirname });
const nodeSymbolGroups = createNodeSymbolGroups(symbols);

const sharedFrontend = requireNodeSharedFrontendRuntime({
  requireModule: require,
  origin: __dirname,
});

const {
  validateTensorShape,
  rowMajorStrides,
  normalizeDim,
  geluScalar,
  siluScalar,
  isGradEnabled,
  is_grad_enabled,
  setGradEnabled,
  set_grad_enabled,
  noGrad,
  no_grad,
  inferenceMode,
  inference_mode,
  enableGrad,
  enable_grad,
  normalizeFactoryShape,
  modelKinds,
  bufferStorageIds,
  programBufferKinds,
  normalizeCompileOptions,
  tokenId,
  tokenSelectionResultFromAbiRecord,
  tokenGenerateResultFromAbiRecord,
  bindLlamaSessionHandleByPolicy,
  safetensorsHeaderBytes,
  safetensorsDataBytes,
  programTraceFromCompileEvidence,
  programTensorProgramIrFromCompileEvidence,
  programKernelPlanFromCompileEvidence,
  programShapeConstraintsFromKernelPlan,
  programParameterLayoutFromKernelPlan,
  programCompatibilityAccepted,
  programCapabilityCanExecute,
  programCapabilityCanBindExternalResources,
  programCapabilityHasFullDispatchPlan,
  programExecutionModeFromCapabilities,
  backendId,
  backendName,
  normalizeWebGpuImportSource,
  programDeviceBufferImportInfo,
  programBufferKindId,
  normalizeLoadModelKind,
  modelLoadKindId,
  packedProgramWeightsLen,
  packedProgramBiasLen,
  programInputShape,
  programOutputShape,
  sessionOutputTensorShape,
  runtimeProfileFromAbiRecord,
  programInspectionFromAbiRecord,
  sessionInspectionFromAbiRecord,
  bufferInspectionFromAbiRecord,
  modelInspectionFromAbiRecord,
  programRequirementsFromAbiRecord,
  llamaKvCacheRequirementsFromAbiRecord,
  programModelCompatibilityFromAbiRecord,
  programExecutionCapabilitiesFromInspection,
  programBufferLayoutFromRequirements,
  programBufferFactorySlotFromRequirements,
  requireProgramBufferResourceFactory,
  assertProgramBufferSlotRequired,
  assertProgramBufferResourceByteLength,
  llamaKvCacheResourceFactory,
  llamaKvCacheResourceSlot,
  llamaProgramKvCacheBufferSlot,
  assertLlamaKvCacheResourceByteLength,
  llamaKvCacheLayoutFromRequirements,
  moduleProgramCompileArtifactsFromCompiledSpec,
  moduleCompatibilityForProgramEvidence,
} = createAdapterSharedFrontendProjection(sharedFrontend);

const {
  autoKind,
  tinyLinearKind,
  tinyLlamaKind,
  smollm135mKind,
  tinyLlama2LayerKind,
  tinyMlpKind,
  moduleKind,
} = adapterModelKindAliases(modelKinds);
const {
  bufferStorageExternalResource,
} = adapterBufferStorageAliases(bufferStorageIds);

let modelHandleForBind;
let modelHandleForCompatibility;

const {
  compileDesc,
  modelInspectionFromNative,
  inspectModelHandle,
  compileModelProgramHandle,
  inspectBufferHandle,
  inspectSessionHandle,
  llamaSessionPosition,
  resetSessionHandle,
  resetSessionRuntimeProfileHandle,
  inspectExecutableProgram,
  programExecutionCapabilities,
  programRequirements,
  programModelCompatibility,
  inspectLlamaProgram,
  programRuntimeProfile,
  sessionRuntimeProfile,
} = createNodeInspectionOps({
  symbols: nodeSymbolGroups.inspection,
  check,
  handleOut,
  readHandle,
  normalizeCompileOptions,
  modelHandleForCompatibility: (model) => modelHandleForCompatibility(model),
  modelInspectionFromAbiRecord,
  bufferInspectionFromAbiRecord,
  sessionInspectionFromAbiRecord,
  programInspectionFromAbiRecord,
  programExecutionCapabilitiesFromInspection,
  programRequirementsFromAbiRecord,
  programModelCompatibilityFromAbiRecord,
  runtimeProfileFromAbiRecord,
});

const nativeLifecycleOps = createNodeNativeLifecycleOps({
  symbols: nodeSymbolGroups.nativeLifecycle,
  check,
});

const {
  rawF32,
  prepareF32,
  f32,
  byteView,
  addTensorGrad,
  requirePositiveInteger,
  zerosF32,
  f32WithLength,
  defaultedF32,
  tensorCoreHelpers,
  tensorMetadataHelpers,
  tensorGradStateHelpers,
  tensorMathSurfaceHelpers,
  sessionTensorHelpers,
  tensorHostSurface,
} = createAdapterTensorRuntimeSurface({
  sharedFrontend,
  Tensor,
  isGradEnabled,
  meanSquaredError: (tensor, target) => meanSquaredError(tensor, target),
  dtype: (tensor) => tensorPlacementHelpers.dtype(tensor),
  device: (tensor) => tensorPlacementHelpers.device(tensor),
  rowMajorStrides,
  normalizeDim,
  isNativeBuffer: (value) => isNativeBuffer(value),
  nativeBufferFromFloat32: (data) => NativeBuffer.fromFloat32(data),
});
let NativeBuffer = AdapterNativeBuffer;
const { isNativeBuffer } = createAdapterNativeBufferInstanceSurface({
  getNativeBufferClass: () => NativeBuffer,
  uninitializedMessage: "Node NativeBuffer instance surface is not initialized",
});
const {
  sessionUploadPersistent,
  sessionUploadPersistentRange,
  stepSession,
  stepNoOutput,
} = createNodeSessionOps({
  symbols: nodeSymbolGroups.session,
  check,
});
const adapterSessionRuntimeSurface = createAdapterSessionRuntimeSurface({
  sharedFrontend,
  isNativeBuffer,
  f32,
  prepareF32,
  valueShape: (value) => value instanceof Tensor ? value.shape : null,
  sessionTensorHelpers,
  assertSessionAlive: (handle) => assertAlive(handle, "session"),
  sessionInspect: inspectSessionHandle,
  sessionUploadPersistent,
  sessionUploadPersistentRange,
  sessionReset: resetSessionHandle,
  sessionRuntimeProfile,
  sessionResetRuntimeProfile: resetSessionRuntimeProfileHandle,
  sessionFree: nativeLifecycleOps.sessionFree,
  nullSessionHandle: null,
  stepSession,
  stepNoOutput,
});
const genericSessionFacade = adapterSessionRuntimeSurface.genericSessionFacade;

const tensorFactoryHelpers = tensorHostSurface.tensorFactoryHelpers;
const tensorViewHelpers = tensorHostSurface.tensorViewHelpers;
const tensorViewSurfaceHelpers = tensorHostSurface.tensorViewSurfaceHelpers;
const tensorPlacementHelpers = tensorHostSurface.tensorPlacementHelpers;
const tensorInfoSurfaceHelpers = tensorHostSurface.tensorInfoSurfaceHelpers;
const tensorJoinHelpers = tensorHostSurface.tensorJoinHelpers;
const tensorIndexHelpers = tensorHostSurface.tensorIndexHelpers;
const tensorIndexSurfaceHelpers = tensorHostSurface.tensorIndexSurfaceHelpers;
const tensorFacade = tensorHostSurface.tensorFacade;
const tensorNativeSurfaceHelpers = tensorHostSurface.tensorNativeSurfaceHelpers;
const tensorStaticHelpers = tensorHostSurface.tensorStaticHelpers;
setAdapterTensorSurfaceHelpers({
  tensorFacade,
  tensorNativeSurfaceHelpers,
  tensorStaticHelpers,
  tensorInfoSurfaceHelpers,
  tensorIndexSurfaceHelpers,
  tensorViewSurfaceHelpers,
  tensorMathSurfaceHelpers,
});
const tensorRootOps = tensorHostSurface.tensorRootOps;
const {
  tensor,
  parameter,
  cat,
  concat,
  concatenate,
  stack,
  vstack,
  hstack,
  einsum,
  full,
  fullLike,
  full_like,
  empty,
  emptyLike,
  empty_like,
  zeros,
  zerosLike,
  zeros_like,
  ones,
  onesLike,
  ones_like,
  eye,
  scalar,
  rand,
  randLike,
  rand_like,
  randn,
  randnLike,
  randn_like,
  randInt,
  randint,
  randPerm,
  randperm,
  manualSeed,
  manual_seed,
  initialSeed,
  initial_seed,
  seededRng,
  linspace,
  arange,
  allclose,
  equal,
  hasShape,
  requireShape,
  to,
  cpu,
  float,
  float32,
  typeAs,
  type_as,
  clone,
  detach,
  reshape,
  view,
  broadcastTo,
  expand,
  repeat,
  tile,
  flatten,
  squeeze,
  unsqueeze,
  transpose,
  permute,
  flip,
  roll,
  select,
  narrow,
  slice,
  indexSelect,
  index_select,
  gather,
  take,
  argsort,
  sort,
  topk,
  scatterAdd,
  scatter_add,
  split,
  chunk,
  unbind,
  add,
  sub,
  mul,
  div,
  eq,
  ne,
  lt,
  le,
  gt,
  ge,
  isclose,
  pow,
  neg,
  negative,
  exp,
  expm1,
  log,
  log1p,
  sqr,
  square,
  recip,
  reciprocal,
  abs,
  sgn,
  sign,
  step,
  isnan,
  isinf,
  isfinite,
  floor,
  ceil,
  round,
  trunc,
  sqrt,
  rsqrt,
  relu,
  gelu,
  silu,
  sigmoid,
  tanh,
  sin,
  cos,
  tan,
  maximum,
  minimum,
  where,
  maskedFill,
  masked_fill,
  sum,
  prod,
  cumsum,
  mean,
  max,
  min,
  any,
  all,
  argmax,
  argmin,
  variance,
  std,
  norm,
  softmax,
  softmax_dim,
  softmaxDim,
  logSoftmax,
  log_softmax,
  log_softmax_dim,
  logSoftmaxDim,
  logsumexp,
  logSumExp,
  clamp,
  clip,
  matmul,
  mm,
  dot,
  trace,
  diagonal,
  bmm,
} = tensorRootOps;

const param = parameter;
const {
  requireNativeBuffer,
  uniqueNativeBuffers,
  bindModuleThroughProgram,
  validateProgramBindParams,
  programBindingPlan,
  prepareProgramBind,
  freeOwnedProgramBindBuffers,
  programNativeBufferBindFields,
} = adapterSessionRuntimeSurface;

const {
  sessionStepToken,
  executeLlamaTokenWindow,
  sessionAdvanceToken,
  llamaArgmaxLogits,
  executeLlamaArgmaxWindow,
  generateLlamaArgmaxWindow,
  llamaSampleLogits,
  executeLlamaSampleWindow,
  generateLlamaSampleWindow,
} = createNodeLlamaTokenOps({
  symbols: nodeSymbolGroups.llamaToken,
  check,
  tokenId,
  isNativeBuffer,
  tokenSelectionResultFromAbiRecord,
  tokenGenerateResultFromAbiRecord,
});

const programBufferFactoriesSlot = createAdapterDeferredSlot("Node Program buffer factories");

const {
  createProgramOutputBuffer,
  createProgramBuffer,
  createProgramKvCacheBuffer,
  createProgramNamedBuffer,
  createProgramLlamaKvCache,
} = createAdapterProgramBufferFactorySurface({
  getProgramBufferFactories: programBufferFactoriesSlot.peek,
  uninitializedMessage: "Node Program buffer factory surface is not initialized",
});

let llamaSessionFacade;
const {
  bindLlamaProgramSession,
  defaultSessionBufferLayout: defaultLlamaSessionBufferLayout,
  createSessionScratch: createLlamaSessionScratch,
  bufferLayout: llamaSessionBufferLayout,
  bufferSlotNames: llamaSessionBufferSlotNames,
  bufferSlot: llamaSessionBufferSlot,
  kvCacheLayout: llamaSessionKvCacheLayout,
  inputLen: llamaSessionInputLen,
  outputLen: llamaSessionOutputLen,
  inputByteLength: llamaSessionInputByteLength,
  outputByteLength: llamaSessionOutputByteLength,
  weightsLen: llamaSessionWeightsLen,
  weightsByteLength: llamaSessionWeightsByteLength,
  biasLen: llamaSessionBiasLen,
  biasByteLength: llamaSessionBiasByteLength,
  parameterLen: llamaSessionParameterLen,
  parameterByteLength: llamaSessionParameterByteLength,
  bufferSizing: llamaSessionBufferSizing,
  matchesBufferSizingSignature: llamaSessionMatchesBufferSizingSignature,
  outputShape: llamaSessionOutputShape,
  stepContract: llamaSessionStepContract,
  preflightStepParams: llamaSessionPreflightStepParams,
  stepParamsCompatibility: llamaSessionStepParamsCompatibility,
  acceptsStepParams: llamaSessionAcceptsStepParams,
  canExecuteStepParams: llamaSessionCanExecuteStepParams,
  requireCanExecuteStepParams: llamaSessionRequireCanExecuteStepParams,
  acceptsAllocationFreeStepParams: llamaSessionAcceptsAllocationFreeStepParams,
  requireAllocationFreeStepParams: llamaSessionRequireAllocationFreeStepParams,
  acceptsRuntimeOutputAllocationFreeStepParams: llamaSessionAcceptsRuntimeOutputAllocationFreeStepParams,
  requireRuntimeOutputAllocationFreeStepParams: llamaSessionRequireRuntimeOutputAllocationFreeStepParams,
  acceptsNoReadbackStepParams: llamaSessionAcceptsNoReadbackStepParams,
  requireNoReadbackStepParams: llamaSessionRequireNoReadbackStepParams,
  acceptsReadbackFreeStepParams: llamaSessionAcceptsReadbackFreeStepParams,
  requireReadbackFreeStepParams: llamaSessionRequireReadbackFreeStepParams,
  acceptsHotStepParams: llamaSessionAcceptsHotStepParams,
  requireHotStepParams: llamaSessionRequireHotStepParams,
  executionPlan: llamaSessionExecutionPlan,
  requireExecutionPlan: llamaSessionRequireExecutionPlan,
  hotPathPlan: llamaSessionHotPathPlan,
  matchesStepContractSignature: llamaSessionMatchesStepContractSignature,
  matchesStepParamsSignature: llamaSessionMatchesStepParamsSignature,
  matchesStepParamsCompatibility: llamaSessionMatchesStepParamsCompatibility,
  position: llamaSessionPositionFacade,
  inspect: inspectLlamaSessionFacade,
  reset: resetLlamaSessionFacade,
  sessionCallProfile: llamaSessionCallProfileFacade,
  matchesSessionCallProfileSignature: llamaSessionMatchesCallProfileSignature,
  resetSessionCallProfile: resetLlamaSessionCallProfileFacade,
  runtimeProfile: llamaSessionRuntimeProfileFacade,
  matchesRuntimeProfileSignature: llamaSessionMatchesRuntimeProfileSignature,
  resetRuntimeProfile: resetLlamaSessionRuntimeProfileFacade,
  free: freeLlamaSessionFacade,
  dispose: disposeLlamaSessionFacade,
  scalarTokenWindow: llamaScalarTokenWindow,
  sessionScalarTokenSampleOptions: llamaScalarTokenSampleOptions,
  sessionNoOutputTokenWindowOptions: llamaNoOutputTokenWindowOptions,
  sessionOutputTokenWindowOptions: llamaOutputTokenWindowOptions,
  sessionScalarTokenExecuteOptions: llamaScalarTokenExecuteOptions,
  sessionScalarTokenOutputOptions: llamaScalarTokenOutputOptions,
  readOutputInto: readLlamaOutputInto,
  readOutputTensor: readLlamaOutputTensor,
  executeTokens: executeLlamaTokens,
  execute: executeLlama,
  executeTensor: executeLlamaTensor,
  executeInto: executeLlamaInto,
  step: stepLlama,
  advance: advanceLlama,
  advanceTokens: advanceLlamaTokens,
  stepTensor: stepLlamaTensor,
  stepInto: stepLlamaInto,
  prefill: prefillLlama,
  prefillTensor: prefillLlamaTensor,
  prefillInto: prefillLlamaInto,
  argmaxToken: argmaxLlamaToken,
  sampleToken: sampleLlamaToken,
  executeTokensArgmax: executeLlamaTokensArgmax,
  stepArgmax: stepLlamaArgmax,
  executeTokensSample: executeLlamaTokensSample,
  stepSample: stepLlamaSample,
  generateTokensArgmax: generateLlamaTokensArgmax,
  generateTokensArgmaxInto: generateLlamaTokensArgmaxInto,
  generateTokensSample: generateLlamaTokensSample,
  generateTokensSampleInto: generateLlamaTokensSampleInto,
} = (llamaSessionFacade = createAdapterLlamaSessionFacadeSurface({
  sharedFrontend,
  isNativeBuffer,
  f32,
  createProgramOutputBuffer,
  sessionTensorHelpers,
  executeTokenWindow: executeLlamaTokenWindow,
  stepToken: sessionStepToken,
  advanceToken: sessionAdvanceToken,
  assertSessionAlive: (handle) => assertAlive(handle, "session"),
  sessionPosition: llamaSessionPosition,
  sessionInspect: inspectSessionHandle,
  sessionReset: resetSessionHandle,
  sessionRuntimeProfile,
  sessionResetRuntimeProfile: resetSessionRuntimeProfileHandle,
  sessionFree: nativeLifecycleOps.sessionFree,
  nullSessionHandle: null,
  argmaxLogits: llamaArgmaxLogits,
  sampleLogits: llamaSampleLogits,
  executeArgmaxWindow: executeLlamaArgmaxWindow,
  executeSampleWindow: executeLlamaSampleWindow,
  generateArgmaxWindow: generateLlamaArgmaxWindow,
  generateSampleWindow: generateLlamaSampleWindow,
}));

const {
  loadModelPath,
  loadSafetensorsDataHandle,
  createTinyLlamaModelHandle,
  probeModelPath,
  probeSafetensorsData,
  probeSafetensorsHeader,
  supportedCheckpointModels,
} = createNodeModelSourceOps({
  symbols: nodeSymbolGroups.modelSource,
  check,
  handleOut,
  readHandle,
  ...createNodeModelSourceBytes(),
  safetensorsDataBytes,
  safetensorsHeaderBytes,
  normalizeLoadModelKind,
  modelLoadKindId,
  modelInspectionFromAbiRecord,
  tinyLlamaKind,
});
const modelSourceFacadeSlot = createAdapterDeferredSlot("Node model-source facade");
const {
  probeModel,
  loadModel,
  loadSafetensorsData,
} = createAdapterModelSourceSurface({
  getModelSourceFacade: modelSourceFacadeSlot.peek,
  uninitializedMessage: "Node model-source surface is not initialized",
});

const {
  llamaKvCacheRequirements,
  bindLlamaSessionHandle,
} = createNodeLlamaSessionBindOps({
  symbols: nodeSymbolGroups.llamaSessionBind,
  check,
  handleOut,
  readHandle,
  requireNativeBuffer,
  isNativeBuffer,
  modelHandleForBind: (model) => modelHandleForBind(model),
  bindLlamaSessionHandleByPolicy,
  llamaKvCacheRequirementsFromAbiRecord,
});

const {
  compileModuleProgram,
  attachProgramCompileEvidence,
  bufferBindDescForTinyLinear,
} = createNodeModuleProgramOps({
  symbols: nodeSymbolGroups.moduleProgram,
  check,
  handleOut,
  readHandle,
  compileDesc,
  moduleProgramCompileArtifactsFromCompiledSpec,
  programNativeBufferBindFields,
  createProgram: createAdapterProgramFactory({
    getProgramClass: () => Program,
  }),
});

const {
  bindProgram,
} = createNodeProgramBindOps({
  symbols: nodeSymbolGroups.programBind,
  check,
  handleOut,
  readHandle,
  prepareProgramBind,
  freeOwnedProgramBindBuffers,
  bufferBindDescForTinyLinear,
  createSession: createAdapterSessionFactory({
    getSessionClass: () => Session,
  }),
});

let nativeBufferFacade;

const nativeBufferSyscalls = createNodeNativeBufferSyscalls({
  symbols: nodeSymbolGroups.nativeBuffer,
  check,
  handleOut,
  readHandle,
});

nativeBufferFacade = createAdapterNativeBufferFacadeSurface({
  sharedFrontend,
  NativeBuffer,
  nullHandle: null,
  f32,
  byteView,
  isLiveHandle: (handle) => Boolean(handle),
  createBuffer: nativeBufferSyscalls.createBuffer,
  wrapBytes: nativeBufferSyscalls.wrapBytes,
  wrapExternalResource: nativeBufferSyscalls.wrapExternalResource,
  bufferSize: nativeBufferSyscalls.bufferSize,
  inspectBuffer: inspectBufferHandle,
  writeBuffer: nativeBufferSyscalls.writeBuffer,
  readBuffer: nativeBufferSyscalls.readBuffer,
  freeBuffer: nativeBufferSyscalls.freeBuffer,
  programDeviceHandle: (...args) => programDeviceHandle(...args),
});
setAdapterNativeBufferFacade(nativeBufferFacade);

const LlamaKvCache = createNodeLlamaKvCacheClass();

const {
  createLlamaKvCache,
  createProgramDeviceKvCache,
  createProgramBufferFactoryKvCache,
} = createNodeLlamaKvCacheOps({
  ...createNodeLlamaKvCacheFactorySurface({
    getNativeBufferClass: () => NativeBuffer,
    getKvCacheClass: () => LlamaKvCache,
  }),
  requireNativeBuffer,
  assertLlamaKvCacheResourceByteLength,
  llamaKvCacheResourceFactory,
  llamaKvCacheResourceSlot,
  llamaKvCacheLayoutFromRequirements,
  llamaKvCacheRequirements,
});

const {
  programCreateOutputBuffer,
  programCreateBuffer,
  programCreateDeviceBuffer,
  programDeviceHandle,
  programImportDeviceBuffer,
} = createNodeProgramBufferOps({
  symbols: nodeSymbolGroups.programBuffer,
  programBufferKinds,
  webgpuImportSourceKey: webgpuInterop.importSource,
  check,
  handleOut,
  readHandle,
  programBufferKindId,
  backendId,
  normalizeWebGpuImportSource,
  programDeviceBufferImportInfo,
  webgpuInterop,
  ...createAdapterProgramBufferNativeBridge({
    getNativeBufferClass: () => NativeBuffer,
  }),
});

const adapterProgramRuntimeSurface = createAdapterProgramRuntimeSurface({
  sharedFrontend,
  assertAlive,
  programDeviceHandle,
  programCreateDeviceBuffer,
  programImportDeviceBuffer,
  isNativeBuffer,
  createProgramDeviceKvCache,
  programRequirements,
  llamaKvCacheRequirements,
  programCreateBuffer,
  programCreateOutputBuffer,
  requireNativeBuffer,
  createProgramBufferFactoryKvCache,
  programModelCompatibility,
  programExecutionCapabilities,
  programRuntimeProfile,
  programResetRuntimeProfile: nativeLifecycleOps.programResetRuntimeProfile,
  programFree: nativeLifecycleOps.programFree,
  nullProgramHandle: null,
  inspectModelHandle,
  compileModelProgramHandle,
  modelFree: nativeLifecycleOps.modelFree,
  nullModelHandle: null,
  inspectExecutableProgram,
  programInputShape,
  programOutputShape,
  createProgramOutputBuffer,
  createProgramNamedBuffer,
  createProgramBuffer,
  bindModuleThroughProgram,
  programBindingPlan,
  createTinyLlamaModelHandle,
  loadModelPath,
  loadSafetensorsDataHandle,
  probeModel,
  probeSafetensorsHeader,
  inspectLlamaProgram,
  createProgramLlamaKvCache,
  bindLlamaProgramSession,
});
const ProgramDevice = adapterProgramRuntimeSurface.ProgramDevice;
programBufferFactoriesSlot.bind(adapterProgramRuntimeSurface.programBufferFactories);
const programFacadePolicy = adapterProgramRuntimeSurface.programFacadePolicy;
const modelFacadePolicy = adapterProgramRuntimeSurface.modelFacadePolicy;
const genericProgramFacade = adapterProgramRuntimeSurface.genericProgramFacade;
const llamaModelFamilyFacade = adapterProgramRuntimeSurface.llamaModelFamilyFacade;
const llamaProgramFacade = adapterProgramRuntimeSurface.llamaProgramFacade;

const {
  TinyLlamaModel,
  TinyLlamaProgram,
  TinyLlamaSession,
  LlamaModel,
  LlamaProgram,
  LlamaSession,
  SmolLM135MModel,
  SmolLM135MProgram,
  SmolLM135MSession,
} = createAdapterLlamaFamilySurface({
  autoKind,
  tinyLlamaKind,
  smollm135mKind,
  llamaModelFamilyFacade,
  llamaProgramFacade,
  bindLlamaSessionHandle,
  defaultLlamaSessionBufferLayout,
  createLlamaSessionScratch,
  assertSessionAlive: (handle) => assertAlive(handle, "session"),
  llamaSessionFacade,
});

const {
  TinyLinearModel,
  TinyMlpModel,
  Program,
  Session,
  TinyLinearProgram,
  TinyLinearSession,
} = createNodeGenericFamilySurface({
  tinyLinearKind,
  tinyMlpKind,
  symbols: nodeSymbolGroups.genericFamily,
  check,
  handleOut,
  readHandle,
  modelFacadePolicy,
  genericProgramFacade,
  genericSessionFacade,
  bindProgram,
  packedProgramWeightsLen,
  packedProgramBiasLen,
  programBufferLayoutFromRequirements,
});

({ modelHandleForBind, modelHandleForCompatibility } = createAdapterModelHandlePolicy({
  sharedFrontend,
  TinyLinearModel,
  TinyMlpModel,
  TinyLlamaModel,
  SmolLM135MModel,
  LlamaModel,
  assertAlive,
}));

const {
  makeParameter,
  parameterView,
  moduleCompileSupport,
  composableModuleCompileSupport,
  resolveParameters,
  parameterNames,
  parameterInfos,
  parameterInfo,
  stateKeys,
  stateData,
  assertStateShape,
  assertStateLayout,
  stateDict,
  loadStateDict,
  zeroGrad,
  setRequiresGrad,
  finiteConfigNumber,
  optimizerStateEntry,
  optimizerStateDict,
  optimizerStateEntries,
  optimizerStepFromState,
  loadOptimizerTensorState,
  rejectUnexpectedOptimizerState,
} = createAdapterModuleStateSurface({
  sharedFrontend,
  Tensor,
  f32WithLength,
  defaultLayout: "row-major",
  optionalParameterFields: true,
});

const { indexValues } = createAdapterIndexValuesSurface({ Tensor });
const traceModuleCompilerSlot = createAdapterDeferredSlot("Node trace Module compiler");
const {
  analyzeSequentialProgram,
  analyzeSingleModuleProgram,
  traceSequentialProgram,
  packedSequentialProgramParameters,
} = createAdapterModuleCompilerSurface({
  getTraceModuleCompiler: traceModuleCompilerSlot.peek,
  uninitializedMessage: "Node Module compiler surface is not initialized",
});

const adapterFrontendModuleSurface = createAdapterFrontendModuleSurface({
  sharedFrontend,
  Tensor,
  f32,
  f32WithLength,
  indexValues,
  addTensorGrad,
  isGradEnabled,
  requirePositiveInteger,
  defaultedF32,
  zerosF32,
  makeParameter,
  parameterView,
  parameterNames,
  parameterInfos,
  parameterInfo,
  zeroGrad,
  setRequiresGrad,
  stateKeys,
  stateDict,
  loadStateDict,
  analyzeSequentialProgram,
  analyzeSingleModuleProgram,
  moduleCompileSupport,
  TinyLinearModel,
  compileModuleProgram,
  attachProgramCompileEvidence,
  packedSequentialProgramParameters,
  traceSequentialProgram,
});
traceModuleCompilerSlot.bind(adapterFrontendModuleSurface.traceModuleCompiler);
const ActivationModule = adapterFrontendModuleSurface.ActivationModule;
const SoftmaxModule = adapterFrontendModuleSurface.SoftmaxModule;
const LogSoftmaxModule = adapterFrontendModuleSurface.LogSoftmaxModule;
const ReductionModule = adapterFrontendModuleSurface.ReductionModule;
const DropoutModule = adapterFrontendModuleSurface.DropoutModule;
const LinearModule = adapterFrontendModuleSurface.LinearModule;
const EmbeddingModule = adapterFrontendModuleSurface.EmbeddingModule;
const Conv2dModule = adapterFrontendModuleSurface.Conv2dModule;
const AvgPool2dModule = adapterFrontendModuleSurface.AvgPool2dModule;
const MaxPool2dModule = adapterFrontendModuleSurface.MaxPool2dModule;
const FeatureNormModule = adapterFrontendModuleSurface.FeatureNormModule;
const ShapeModule = adapterFrontendModuleSurface.ShapeModule;
const SequentialModule = adapterFrontendModuleSurface.SequentialModule;

const {
  traceModule,
  compileSupportForModule,
  requireCompileSupportForModule,
  compilerSignaturesForModule,
  tensorProgramIrForModule,
  kernelPlanForModule,
  bufferLayoutForModule,
  memoryLayoutForModule,
  inputShapeForModule,
  outputShapeForModule,
  shapeConstraintsForModule,
  parameterLayoutForModule,
  explainModule,
  requireCompilePlanForModule,
  canCompileModule,
  compileModule,
  bindModuleParameters,
  placeModuleParameters,
  bindingPlanForModuleBindings,
  requireBindingPlanForModuleBindings,
} = adapterFrontendModuleSurface.moduleFacadeHelpers;

const publicNamespaces = createAdapterFrontendNamespaces({
  sharedFrontend,
  Tensor,
  f32,
  f32WithLength,
  indexValues,
  addTensorGrad,
  isGradEnabled,
  makeParameter,
  zeroGrad,
  resolveParameters,
  finiteConfigNumber,
  optimizerStateEntry,
  optimizerStateDict,
  optimizerStateEntries,
  optimizerStepFromState,
  loadOptimizerTensorState,
  rejectUnexpectedOptimizerState,
  LinearModule,
  EmbeddingModule,
  Conv2dModule,
  AvgPool2dModule,
  MaxPool2dModule,
  SequentialModule,
  ActivationModule,
  SoftmaxModule,
  LogSoftmaxModule,
  ReductionModule,
  DropoutModule,
  ShapeModule,
  FeatureNormModule,
  geluScalar,
  siluScalar,
  resolveParameters,
  parameterNames,
  parameterInfos,
  parameterInfo,
  zeroGrad,
  setRequiresGrad,
  stateDict,
  loadStateDict,
  traceSequentialProgram,
  traceModule,
  compileSupportForModule,
  requireCompileSupportForModule,
  compilerSignaturesForModule,
  tensorProgramIrForModule,
  kernelPlanForModule,
  bufferLayoutForModule,
  memoryLayoutForModule,
  inputShapeForModule,
  outputShapeForModule,
  shapeConstraintsForModule,
  parameterLayoutForModule,
  explainModule,
  requireCompilePlanForModule,
  canCompileModule,
  compileModule,
  bindModuleParameters,
  placeModuleParameters,
  bindingPlanForModuleBindings,
  requireBindingPlanForModuleBindings,
  tensor,
  stack,
});
const {
  meanSquaredError,
  classTargets,
  crossEntropy,
  loss,
  train,
  data,
  SgdOptimizer,
  AdamOptimizer,
  AdamWOptimizer,
  RMSpropOptimizer,
  AdagradOptimizer,
  nn,
  optim,
  checkpoint,
} = publicNamespaces;
const F = nn.F;
const compile = createAdapterCompileNamespace({
  traceSequentialProgram,
  analyzeSequentialProgram,
  compileModuleProgram,
});
sharedFrontend.lazy.setLazyTensorProgramCompiler((lazyGraph, compileOptions) => compile.compile(lazyGraph, compileOptions));
const torchCheckpointIo = createAdapterTorchCheckpointIo(checkpoint, {
  readTextFile: (path) => readFileSync(path, "utf8"),
  writeTextFile: (path, text) => writeFileSync(path, text, "utf8"),
});
const gradMode = createAdapterGradModeSurface({
  isGradEnabled,
  is_grad_enabled,
  setGradEnabled,
  set_grad_enabled,
  noGrad,
  no_grad,
  inferenceMode,
  inference_mode,
  enableGrad,
  enable_grad,
});
const torch = createAdapterTorchNamespace({
  Tensor,
  tensor,
  parameter,
  param,
  factories: {
    empty,
    emptyLike,
    empty_like,
    zeros,
    zerosLike,
    zeros_like,
    ones,
    onesLike,
    ones_like,
    full,
    fullLike,
    full_like,
    eye,
    scalar,
    rand,
    randLike,
    rand_like,
    randn,
    randnLike,
    randn_like,
    randint,
    randInt,
    randperm,
    randPerm,
    manual_seed,
    manualSeed,
    initialSeed,
    initial_seed,
    seededRng,
    arange,
    linspace,
    cat,
    concat,
    concatenate,
    stack,
    vstack,
    hstack,
    einsum,
    broadcastTo,
    expand,
    repeat,
    tile,
    scatterAdd,
    scatter_add,
    add,
    sub,
    mul,
    div,
    eq,
    ne,
    lt,
    le,
    gt,
    ge,
    isclose,
    matmul,
    mm,
    dot,
    trace,
    diagonal,
    bmm,
    clone,
    detach,
  },
  shape: { hasShape, requireShape },
  grad: {
    no_grad,
    noGrad,
    inference_mode,
    inferenceMode,
    enable_grad,
    enableGrad,
    is_grad_enabled,
    isGradEnabled,
    set_grad_enabled,
    setGradEnabled,
  },
  gradMode,
  nn,
  F,
  compile,
  lazy: sharedFrontend.lazy,
  optim,
  data,
  loss,
  train,
  checkpoint,
  checkpointIo: torchCheckpointIo,
  Program,
  Session,
  NativeBuffer,
});

const { readSafetensorsHeaderFile } = createAdapterSafetensorsFileHeaderHelpers(fs);

modelSourceFacadeSlot.bind(createAdapterModelSourceFacade({
  readSafetensorsHeaderFile,
  probeModelPath,
  probeSafetensorsData,
  probeSafetensorsHeader,
  loadModelPath,
  loadSafetensorsDataHandle,
  tinyLlama2LayerKind,
  LlamaModel,
  TinyLlamaModel,
  SmolLM135MModel,
}));

module.exports = createAdapterPublicRuntimeExports({
  Tensor,
  tensor,
  asTensor: tensor,
  as_tensor: tensor,
  asarray: tensor,
  fromNumpy: tensor,
  from_numpy: tensor,
  parameter,
  param,
  cat,
  concat,
  concatenate,
  stack,
  vstack,
  hstack,
  einsum,
  allclose,
  equal,
  to,
  cpu,
  float,
  float32,
  typeAs,
  type_as,
  clone,
  detach,
  reshape,
  view,
  broadcastTo,
  expand,
  repeat,
  tile,
  flatten,
  squeeze,
  unsqueeze,
  transpose,
  permute,
  flip,
  roll,
  select,
  narrow,
  slice,
  indexSelect,
  index_select,
  gather,
  take,
  argsort,
  sort,
  topk,
  scatterAdd,
  scatter_add,
  split,
  chunk,
  unbind,
  add,
  sub,
  mul,
  div,
  isGradEnabled,
  is_grad_enabled,
  setGradEnabled,
  set_grad_enabled,
  noGrad,
  no_grad,
  inferenceMode,
  inference_mode,
  enableGrad,
  enable_grad,
  gradMode,
  torch,
  eq,
  ne,
  lt,
  le,
  gt,
  ge,
  isclose,
  pow,
  neg,
  negative,
  exp,
  expm1,
  log,
  log1p,
  sqr,
  square,
  recip,
  reciprocal,
  abs,
  sgn,
  sign,
  step,
  isnan,
  isinf,
  isfinite,
  floor,
  ceil,
  round,
  trunc,
  sqrt,
  rsqrt,
  relu,
  gelu,
  silu,
  sigmoid,
  tanh,
  sin,
  cos,
  tan,
  maximum,
  minimum,
  where,
  maskedFill,
  masked_fill,
  sum,
  prod,
  cumsum,
  mean,
  max,
  min,
  any,
  all,
  argmax,
  argmin,
  variance,
  std,
  norm,
  softmax,
  softmax_dim,
  softmaxDim,
  logSoftmax,
  log_softmax,
  log_softmax_dim,
  logSoftmaxDim,
  logsumexp,
  logSumExp,
  clamp,
  clip,
  matmul,
  mm,
  dot,
  trace,
  diagonal,
  bmm,
  full,
  fullLike,
  full_like,
  empty,
  emptyLike,
  empty_like,
  zeros,
  zerosLike,
  zeros_like,
  ones,
  onesLike,
  ones_like,
  eye,
  scalar,
  rand,
  randLike,
  rand_like,
  randn,
  randnLike,
  randn_like,
  randInt,
  randint,
  randPerm,
  randperm,
  manualSeed,
  manual_seed,
  initialSeed,
  initial_seed,
  seededRng,
  hasShape,
  requireShape,
  linspace,
  arange,
  nn,
  F,
  data,
  loss,
  optim,
  train,
  checkpoint,
  save: torch.save,
  load: torch.load,
  compile,
  TinyLinear: TinyLinearModel,
  TinyMlp: TinyMlpModel,
  TinyLlama: TinyLlamaModel,
  SmolLM135M: SmolLM135MModel,
  Llama: LlamaModel,
  probeModel,
  probeSafetensorsData,
  probeSafetensorsHeader,
  supportedCheckpointModels,
  loadModel,
  loadSafetensorsData,
  TinyLinearModel,
  TinyMlpModel,
  Program,
  Session,
  TinyLinearProgram,
  TinyLinearSession,
  TinyLlamaModel,
  TinyLlamaProgram,
  TinyLlamaSession,
  SmolLM135MModel,
  SmolLM135MProgram,
  SmolLM135MSession,
  LlamaModel,
  LlamaProgram,
  LlamaSession,
  NativeBuffer,
  ProgramDevice,
  LlamaKvCache,
  ZgmlError,
  runtimeInfo,
  abiStructSize,
  abiStructSizes,
  loadedRuntimeInfo,
  webgpuInterop,
}, "Node public runtime exports");
