"use strict";

// Generated by scripts/generate_native_runtime_wrappers.cjs from src/ts/runtime/native_api_contract.ts.
// The native package spine contract wrapper intentionally has no hand-maintained root export list.
import { frontendManifest } from "../frontend_manifest.js";

export const nativePackageSpineContractManifest = Object.freeze({
  kind: "zgml-native-package-spine-contract",
  source: "generated-ts",
  generator: "scripts/generate_native_runtime_wrappers.cjs",
  policyOwner: "src/ts/runtime/native_api_contract.ts",
  generatedFrom: "src/ts/runtime/native_api_contract.ts",
  productSourceOfTruth: frontendManifest.productSourceOfTruth,
  nativeProductPolicy: frontendManifest.nativeProductPolicy,
  handwrittenRootExportList: false,
});

export const requiredNativePackageSpineExports = Object.freeze([
  "frontendManifest",
  "nodeAdapterEvidence",
  "nativeAdapterEvidence",
  "resolveNativeLibraryPath",
  "tensor",
  "gradMode",
  "simple",
  "zgml",
  "torch",
  "nn",
  "F",
  "data",
  "loss",
  "optim",
  "train",
  "checkpoint",
  "save",
  "load",
  "compile",
  "native",
  "inference",
  "forInference",
  "for_inference",
  "compileInference",
  "compile_inference",
  "compileForInference",
  "compile_for_inference",
  "trainingStep",
  "training_step",
  "compileForTraining",
  "compile_for_training",
  "program",
  "session",
  "stepParams",
  "compile",
] as const);

export type NativePackageSpineContractManifest = typeof nativePackageSpineContractManifest;
export type RequiredNativePackageSpineExport = typeof requiredNativePackageSpineExports[number];
