#!/usr/bin/env node
"use strict";

const fs = require("fs");
const path = require("path");
const {
  nativeApiContractArrays,
  nativeApiContractManifestPolicy,
  nativePackageSpineExports,
  nativeRootOverrideExports,
} = require("./native_api_contract_policy.cjs");

const root = path.resolve(__dirname, "..");
const contractPath = path.join(root, "src", "ts", "runtime", "native_api_contract.ts");
const frontendPath = path.join(root, "src", "ts", "index.ts");
const nodePath = path.join(root, "src", "ts", "node.ts");
const bunPath = path.join(root, "src", "ts", "bun.ts");
const bunNativePath = path.join(root, "src", "ts", "bun_native.ts");
const packageSpinePath = path.join(root, "src", "ts", "runtime", "native_package_spine_contract.ts");
const nodeRuntimePath = path.join(root, "src", "ts", "adapters", "node_native_runtime.ts");
const bunRuntimePath = path.join(root, "src", "ts", "adapters", "bun_native_runtime.ts");
const check = process.argv.includes("--check");
const nativeApiContractSource = fs.readFileSync(contractPath, "utf8");
const nativeApiArrays = nativeApiContractArrays(nativeApiContractSource);
const nativeApiManifestPolicy = nativeApiContractManifestPolicy(nativeApiContractSource);

function generatedHeader(kind) {
  return [
    `"use strict";`,
    "",
    `// Generated by scripts/generate_native_runtime_wrappers.cjs from src/ts/runtime/native_api_contract.ts.`,
    `// The ${kind} wrapper intentionally has no hand-maintained root export list.`,
    "",
  ].join("\n");
}

function exportLines(runtimeName, exports) {
  return exports.map((name) => {
    if (name === "webgpuInterop") {
      return `export const webgpuInterop: NativeRuntime["webgpuInterop"] = ${runtimeName}.webgpuInterop;`;
    }
    return `export const ${name} = ${runtimeName}.${name};`;
  }).join("\n");
}

function nodeSource(exports) {
  return `${generatedHeader("Node")}import {
  requireNodeConcreteRuntimeByPolicy,
  type NativeRuntime,
} from "./node_concrete_runtime.js";

declare const __dirname: string;
declare const require: {
  (id: string): any;
  resolve(id: string): string;
};

export type NativeNodeRuntime = NativeRuntime;

export const nativeNodeRuntime: NativeNodeRuntime = requireNodeConcreteRuntimeByPolicy({
  requireModule: require,
  origin: __dirname,
});

${exportLines("nativeNodeRuntime", exports)}
`;
}

function bunSource(exports) {
  return `${generatedHeader("Bun")}/// <reference path="./node_module_ambient.d.ts" />

import { createRequire } from "node:module";
import { pathToFileURL } from "node:url";
import {
  requireBunConcreteRuntimeByPolicy,
  type NativeRuntime,
} from "./bun_concrete_runtime.js";

declare const __filename: string;
declare const __dirname: string;

const requireModule = createRequire(pathToFileURL(__filename).href);

export type NativeBunRuntime = NativeRuntime;

export const nativeBunRuntime: NativeBunRuntime = requireBunConcreteRuntimeByPolicy({
  requireModule,
  origin: __dirname,
});

${exportLines("nativeBunRuntime", exports)}
`;
}

function rootSource(kind, adapterModule, runtimeModule, runtimeOverrides) {
  return `${generatedHeader(kind)}export * from "./index.js";
export * from "./adapters/${adapterModule}.js";
export * from "./adapters/${runtimeModule}.js";
export {
${runtimeOverrides.map((name) => `  ${name},`).join("\n")}
} from "./adapters/${runtimeModule}.js";
`;
}

function frontendRootSource(kind, adapterModule) {
  return `${generatedHeader(kind)}export * from "./index.js";
export * from "./adapters/${adapterModule}.js";
`;
}

function packageSpineSource(exports, manifestPolicy) {
  return `${generatedHeader("native package spine contract")}import { frontendManifest } from "../frontend_manifest.js";

export const nativePackageSpineContractManifest = Object.freeze({
  kind: "zgml-native-package-spine-contract",
  source: "generated-ts",
  generator: "scripts/generate_native_runtime_wrappers.cjs",
  policyOwner: "${manifestPolicy.policyOwner}",
  generatedFrom: "${manifestPolicy.policyOwner}",
  productSourceOfTruth: frontendManifest.productSourceOfTruth,
  nativeProductPolicy: frontendManifest.nativeProductPolicy,
  handwrittenRootExportList: false,
});

export const requiredNativePackageSpineExports = Object.freeze([
${exports.map((name) => `  "${name}",`).join("\n")}
] as const);

export type NativePackageSpineContractManifest = typeof nativePackageSpineContractManifest;
export type RequiredNativePackageSpineExport = typeof requiredNativePackageSpineExports[number];
`;
}

function checkOrWrite(filePath, expected) {
  if (check) {
    const actual = fs.readFileSync(filePath, "utf8");
    if (actual !== expected) {
      console.error(`${path.relative(root, filePath)} is out of date; run npm run generate:native-runtime-wrappers`);
      process.exitCode = 1;
    }
    return;
  }
  fs.writeFileSync(filePath, expected);
}

const nativeExports = nativeApiArrays.requiredNativeApiExports;
const runtimeOverrides = nativeRootOverrideExports(
  nativeExports,
  fs.readFileSync(frontendPath, "utf8"),
  nativeApiArrays.requiredNativeFrontendNamespaceExports,
);
const packageSpineExports = nativePackageSpineExports(nativeApiArrays, runtimeOverrides);
checkOrWrite(nodeRuntimePath, nodeSource(nativeExports));
checkOrWrite(bunRuntimePath, bunSource(nativeExports));
checkOrWrite(nodePath, rootSource("Node root", "node", "node_native_runtime", runtimeOverrides));
checkOrWrite(bunPath, frontendRootSource("Bun frontend root", "bun"));
checkOrWrite(bunNativePath, rootSource("Bun native root", "bun", "bun_native_runtime", runtimeOverrides));
checkOrWrite(packageSpinePath, packageSpineSource(packageSpineExports, nativeApiManifestPolicy));
if (process.exitCode) process.exit(process.exitCode);
console.log(`native runtime wrappers ${check ? "checked" : "generated"}: ${nativeExports.length} exports, ${runtimeOverrides.length} root overrides, ${packageSpineExports.length} package spine exports`);
