"use strict";

import { tsProductManifestPolicy } from "./internal/product_manifest.js";

export const inspectionManifest = Object.freeze({
  kind: "zgml-inspection",
  ...tsProductManifestPolicy("src/ts/inspection.ts"),
  runtimePath: "Program -> Session -> inspection evidence",
});

export {
  acceptsModuleBindingPlan,
  acceptsModuleCompilePlan,
  acceptsProgramBindingPlan,
  acceptsProgramExecutionPlan,
  acceptsSessionExecutionPlan,
  assert_module_binding_plan,
  assert_module_compile_plan,
  assert_program_binding_plan,
  assert_program_execution_plan,
  assert_session_execution_plan,
  assertModuleBindingPlan,
  assertModuleCompilePlan,
  assertProgramBindingPlan,
  assertProgramExecutionPlan,
  assertSessionExecutionPlan,
  matchesModuleCompilePlanSignature,
  matchesModuleBindingPlanSignature,
  matchesProgramBindingPlanSignature,
  matchesProgramExecutionPlanSignature,
  matchesSessionExecutionPlanSignature,
  requireModuleBindingPlan,
  requireModuleCompilePlan,
  requireProgramBindingPlan,
  requireProgramExecutionPlan,
  requireSessionExecutionPlan,
} from "./runtime/execution_plan.js";
export {
  acceptsKernelPlan,
  assert_kernel_plan,
  assertKernelPlan,
  matchesKernelPlanSignature,
  requireKernelPlan,
} from "./runtime/kernel_plan.js";
export {
  acceptsSessionCallProfile,
  assert_session_call_profile,
  assertSessionCallProfile,
  matchesSessionCallProfileSignature,
  requireSessionCallProfile,
} from "./runtime/session_profile.js";
export {
  bufferInspectionFromAbiRecord,
  bufferInspectionFromAbiWords,
  llamaKvCacheRequirementsFromAbiRecord,
  llamaKvCacheRequirementsFromAbiWords,
  modelInspectionFromAbiRecord,
  modelInspectionFromAbiWords,
  programCapabilityCanBindExternalResources,
  programCapabilityCanExecute,
  programCapabilityHasFullDispatchPlan,
  programCompatibilityAccepted,
  programExecutionCapabilitiesFromInspection,
  programExecutionMode,
  programExecutionModeFromCapabilities,
  programInspectionFromAbiRecord,
  programInspectionFromAbiWords,
  programModelCompatibilityFromAbiRecord,
  programModelCompatibilityFromAbiWords,
  programRequirementsFromAbiRecord,
  programRequirementsFromAbiWords,
  programRuntimeDiagnostics,
  acceptsRuntimeProfile,
  assert_runtime_profile,
  assertRuntimeProfile,
  matchesRuntimeProfileSignature,
  requireRuntimeProfile,
  requireNoFallbackRuntimeProfile,
  requireNoSyncRuntimeProfile,
  requireHotRuntimeProfile,
  requireRuntimePatchValidProfile,
  runtimeProfileFromAbiRecord,
  runtimeProfileFromAbiWords,
  runtimeProfileExpectation,
  runtimeProfileHasNoFallback,
  runtimeProfileHasNoInvalidRuntimePatches,
  runtimeProfileHasNoSync,
  sessionInspectionFromAbiRecord,
  sessionInspectionFromAbiWords,
} from "./runtime/inspection.js";
