"use strict";

import { tsProductManifestPolicy } from "./internal/product_manifest.js";

export const nativeBufferManifest = Object.freeze({
  kind: "zgml-native-buffer",
  ...tsProductManifestPolicy("src/ts/native_buffer.ts"),
  runtimePath: "Program -> Session -> NativeBuffer",
});

export type {
  ExternalResourceAccess,
  ExternalResourceAccessName,
  ExternalResourceOptions,
  HostGpuBufferImportSource,
  NativeBuffer,
  NativeBufferByteRangeElementType,
  NativeBufferByteRangeInfo,
  NativeBufferByteRangeOperation,
  NativeBufferDeviceImportInfo,
  NativeBufferExternalResourceInfo,
  ProgramDeviceBufferImportDescriptor,
  ProgramDeviceBufferImportInfo,
  ProgramDeviceBufferImportOptions,
  ProgramDeviceBufferImportSource,
  ProgramDeviceImportBufferSource,
  WebGpuInteropImportFields,
  WebGpuInteropImportSource,
  WebGpuInteropSymbols,
} from "./public_api.js";

export {
  assert_native_buffer_device_import_info,
  assert_native_buffer_external_resource_info,
  assert_native_buffer_byte_range_info,
  assert_program_device_buffer_import_info,
  assertNativeBufferDeviceImportInfo,
  assertNativeBufferExternalResourceInfo,
  assertNativeBufferByteRangeInfo,
  assertProgramDeviceBufferImportInfo,
  externalResourceInfo,
  isNativeBufferDeviceImportInfo,
  isNativeBufferExternalResourceInfo,
  isNativeBufferByteRangeInfo,
  isProgramDeviceBufferImportInfo,
  matches_native_buffer_device_import_signature,
  matches_native_buffer_external_resource_signature,
  matches_native_buffer_byte_range_signature,
  matches_program_device_buffer_import_signature,
  matchesNativeBufferDeviceImportSignature,
  matchesNativeBufferExternalResourceSignature,
  matchesNativeBufferByteRangeSignature,
  matchesProgramDeviceBufferImportSignature,
  nativeBufferByteRangeInfo,
  nativeBufferCreateByteLength,
  nativeBufferDeviceImportOptions,
  nativeBufferDeviceImportSignature,
  nativeBufferExternalResourceSignature,
  nativeBufferReadBytesIntoInfo,
  nativeBufferReadBytesTarget,
  nativeBufferReadFloat32IntoInfo,
  nativeBufferReadFloat32Target,
  nativeBufferWrapByteLength,
  nativeBufferWriteInfo,
  normalizeWebGpuImportSource,
  programDeviceBufferImportInfo,
  programDeviceBufferImportSignature,
  readImportField,
  readImportString,
  requireNativeBufferDeviceImportInfo,
  requireNativeBufferExternalResourceInfo,
  requireNativeBufferByteRangeInfo,
  requireProgramDeviceBufferImportInfo,
  validateNativeBufferReadBytesInto,
  validateNativeBufferReadFloat32Into,
  validateNativeBufferWrapFloat32,
  createNativeBufferFacadeHelpers,
  createNativeBufferLifetimeHelpers,
} from "./runtime/native_buffer.js";
