"use strict";

import { tsProductManifestPolicy } from "./internal/product_manifest.js";

export type {
  LlamaSessionStepContract,
  LlamaStepParams,
  ProgramInputBinding,
  ProgramOutputBinding,
  SessionExecuteIntoParams,
  SessionExecuteParams,
  SessionExecuteTensorParams,
  SessionExecutionPlan,
  SessionNoOutputEffect,
  SessionStepContract,
  SessionStepParams,
  SessionStepParamsCompatibility,
  SessionStepParamsDiagnostic,
  SessionStepParamsDiagnosticCode,
  SessionStepParamsElementType,
  SessionStepParamsHotPathBlocker,
  SessionStepParamsHotPathStatus,
  SessionStepParamsInputOwnership,
  SessionStepParamsInputSource,
  SessionStepParamsOutputEffect,
  SessionStepParamsOutputOwnership,
  SessionStepParamsOutputReturnOwnership,
  SessionStepParamsOutputTarget,
  SessionStepParamsStateEffect,
} from "./public_api.js";

export const stepParamsManifest = Object.freeze({
  kind: "zgml-step-params",
  ...tsProductManifestPolicy("src/ts/step_params.ts"),
  runtimePath: "Program -> Session -> StepParams",
});

export {
  acceptsAllocationFreeStepParamsCompatibility,
  acceptsHotStepParamsCompatibility,
  acceptsNoReadbackStepParamsCompatibility,
  acceptsReadbackFreeStepParamsCompatibility,
  acceptsRuntimeOutputAllocationFreeStepParamsCompatibility,
  acceptsStepParamsCompatibility,
  assertFloat32OutputBuffer,
  assertNoInlineOutput,
  canExecuteStepParamsCompatibility,
  copyTokenWindowOptions,
  freezeStepParamsDiagnostics,
  frozenShapeEvidence,
  assert_step_params_compatibility,
  assertStepParamsCompatibility,
  isStepParamsCompatibility,
  matchesStepContractSignature,
  matchesStepParamsCompatibility,
  matchesStepParamsSignature,
  noOutputTokenWindowOptions,
  outputTokenWindowOptions,
  requireAllocationFreeStepParamsCompatibility,
  requireCanExecuteStepParamsCompatibility,
  requireHotStepParamsCompatibility,
  requireNoReadbackStepParamsCompatibility,
  requireReadbackFreeStepParamsCompatibility,
  requireRuntimeOutputAllocationFreeStepParamsCompatibility,
  requireStepParamsCompatibility,
  scalarTokenExecuteOptions,
  scalarTokenOutputOptions,
  scalarTokenSampleOptions,
  shapeSignature,
  stepParamsCompatibilityResult,
  stepParamsDiagnosticCode,
  stepParamsDiagnosticDetails,
  stepParamsHotPathBlockers,
  stepParamsHotPathStatus,
  stepParamsInputOwnership,
  stepParamsOutputEffect,
  stepParamsOutputOwnership,
  stepParamsOutputReturnOwnership,
  stepParamsValidationError,
  validateExecuteStepParams,
  validateLlamaTokenStepParams,
  validateLogitsOutputBuffer,
  validateTokenWindowFitsContract,
} from "./runtime/step_params.js";
