"use strict";

import { tsProductManifestPolicy } from "./internal/product_manifest.js";

export {
  assert_train_evaluate_evidence,
  assert_train_evaluate_step_evidence,
  assert_train_fit_evidence,
  assert_train_fit_step_evidence,
  assert_train_predict_evidence,
  assert_train_predict_step_evidence,
  assert_train_step_evidence,
  assertTrainEvaluateEvidence,
  assertTrainEvaluateStepEvidence,
  assertTrainFitEvidence,
  assertTrainFitStepEvidence,
  assertTrainPredictEvidence,
  assertTrainPredictStepEvidence,
  assertTrainStepEvidence,
  createLossTrainHelpers,
  isTrainEvaluateEvidence,
  isTrainEvaluateStepEvidence,
  isTrainFitEvidence,
  isTrainFitStepEvidence,
  isTrainPredictEvidence,
  isTrainPredictStepEvidence,
  isTrainStepEvidence,
  matches_train_evaluate_evidence_signature,
  matches_train_evaluate_step_evidence_signature,
  matches_train_fit_evidence_signature,
  matches_train_fit_step_evidence_signature,
  matches_train_predict_evidence_signature,
  matches_train_predict_step_evidence_signature,
  matches_train_step_evidence_signature,
  matchesTrainEvaluateEvidenceSignature,
  matchesTrainEvaluateStepEvidenceSignature,
  matchesTrainFitEvidenceSignature,
  matchesTrainFitStepEvidenceSignature,
  matchesTrainPredictEvidenceSignature,
  matchesTrainPredictStepEvidenceSignature,
  matchesTrainStepEvidenceSignature,
  requireTrainEvaluateEvidence,
  requireTrainEvaluateStepEvidence,
  requireTrainFitEvidence,
  requireTrainFitStepEvidence,
  requireTrainPredictEvidence,
  requireTrainPredictStepEvidence,
  requireTrainStepEvidence,
} from "./train/loss_train_helpers.js";

export type {
  PublicTrainNamespace,
  TrainBatchInputShape,
  TrainBatchTargetShape,
  TrainClassificationBatch,
  TrainClassificationClassMetric,
  TrainClassificationReport,
  TrainClassificationTargetShape,
  TrainEvaluateContext,
  TrainEvaluateEvidence,
  TrainEvaluateOptions,
  TrainEvaluateStepEvidence,
  TrainEarlyStoppingOptions,
  TrainFitContext,
  TrainPredictContext,
  TrainPredictEvidence,
  TrainPredictOptions,
  TrainPredictStepEvidence,
  TrainFitEvidence,
  TrainFitOptions,
  TrainFitStepEvidence,
  TrainGradientClipOptions,
  TrainLossStepOptions,
  TrainModuleOutputShape,
  TrainModelFitOptions,
  NativeTrainingBulkFitPlan,
  NativeTrainingExplanation,
  TrainNamespace,
  TrainClassificationCriterion,
  TrainStepOptions,
  TrainStepEvidence,
  TrainSupervisedCriterion,
  TrainSupervisedBatch,
} from "./public_api.js";

export const trainManifest = Object.freeze({
  kind: "zgml-train",
  ...tsProductManifestPolicy("src/ts/train.ts"),
  factory: "createLossTrainHelpers",
});
